#
# TABLE STRUCTURE FOR: books
#

DROP TABLE IF EXISTS `books`;

CREATE TABLE `books` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `date` date DEFAULT NULL,
  `autor` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (1, 'Ut sed sint earum quia assumenda quasi consequatur. Voluptatem qui sint iusto et qui accusantium incidunt vitae.', '1993-06-27', 'Mikel', 'Dolores nulla maiores quo omnis aspernatur eligendi harum. Et enim quis voluptatem facere tempore architecto enim. Eos vel inventore accusantium mollitia aut provident tempora atque.', 'tmp//cc99feb9ef78d8607cb79cf774460395.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (2, 'Eum possimus nihil sint incidunt. Sapiente modi repellendus harum harum illo. Ratione cum repellat odio nulla. Voluptatem dolorum corporis id labore veniam.', '1974-09-04', 'Dexter', 'Vero dignissimos et sed aut. Totam doloremque qui nisi qui ipsum unde sunt consequatur. Consequatur mollitia doloribus ut esse molestiae error. Cum itaque dolores magnam exercitationem in ex.', 'tmp//e552130e1913b7f37ffe56b8e1c8be61.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (3, 'Autem architecto sit qui consequatur reiciendis. Tempora sequi sit beatae ipsum eius fugit. Est cupiditate possimus deserunt iste.', '1984-10-20', 'Derek', 'Modi libero enim perspiciatis consectetur fuga. Dolorem voluptatum velit quos officia.\nUllam dolorum laudantium mollitia vel sit deserunt. Atque ut soluta ullam amet.', 'tmp//1538c900b42b34277e999fecf1be3399.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (4, 'Corrupti consequatur ut iste ut et veniam. Est recusandae quo repellendus quia. Et praesentium incidunt ullam velit numquam.', '1996-11-25', 'Abe', 'Aut qui culpa ex praesentium dolores ad. Cupiditate est fugiat eos quia cumque. Iusto eius libero tempore occaecati ad quod. Non sunt est dicta neque quia perferendis.', 'tmp//8b2c64f590a511a3b863449f69976cce.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (5, 'Voluptate ut omnis occaecati provident. Distinctio rem iusto facere omnis modi enim aut. Suscipit sequi qui qui maxime vel esse impedit et. Porro est velit doloribus dolorem magni adipisci voluptas.', '1988-07-02', 'Taurean', 'Ea eaque aliquam repellendus. Magni vel deserunt voluptas et est asperiores harum sint. Temporibus eum corporis voluptate occaecati libero excepturi cupiditate.', 'tmp//412465696fe6727d024b6138d5d181dc.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (6, 'Voluptate vel odit fugit excepturi. Atque aperiam est rerum sunt inventore aut. Aut et aut est doloremque harum inventore. Quis aut iure est repellendus veritatis vel.', '2001-10-27', 'Elvis', 'Natus illum provident aliquid veniam animi possimus temporibus. Sunt rerum vel molestiae voluptatem. Dolorem ratione nihil blanditiis autem aspernatur animi. Natus earum voluptas rem reiciendis.', 'tmp//060a7988398c731541fb7ce86ffdbc79.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (7, 'Exercitationem vel necessitatibus consequatur magnam quaerat dolorum. Accusamus et velit aut tenetur. Molestiae dolorem et deleniti magni voluptatibus. Illo alias velit consectetur velit.', '1991-07-01', 'Christ', 'Necessitatibus vero in velit nulla. Temporibus excepturi non et expedita nihil ex. Iusto nulla quibusdam ratione repudiandae saepe omnis iste.', 'tmp//ea3eacb105453c2659a045c919ab83a0.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (8, 'Nulla est optio modi qui. Natus modi a nostrum odit et ut aut. Corrupti in consectetur est nobis aut rem.', '1984-01-03', 'Martin', 'Repudiandae voluptas sed quia commodi natus. Ab quo sit corporis cum cumque consequatur. Et omnis et commodi rerum natus natus illum.', 'tmp//3654b898a1c625920fa1f491c8a3c598.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (9, 'Inventore recusandae et aut fuga atque aut. Quis temporibus quia magnam commodi. Et nam recusandae natus quam nemo. Quasi ipsam omnis eos.', '1971-08-10', 'Tillman', 'Officiis quas et commodi provident amet quo. Ut dolor nemo voluptas consequatur. Placeat rerum ad voluptatem quia.', 'tmp//94523cb14b09d875812001d7fa99ce11.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (10, 'Illo voluptatum ipsa dolorem consequatur qui. Sit laudantium alias quo aut voluptatem iusto. Quod et nemo sit qui eum et ut. Deserunt asperiores accusantium quidem.', '1995-11-05', 'Benjamin', 'Minima sint voluptatem dolor. Soluta vel velit molestiae fugiat sit libero. Repellendus ea voluptas sit iure doloremque perferendis.', 'tmp//48f251a095e2f0cb6ae678fbad2a8785.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (11, 'Vel ad mollitia deleniti corrupti soluta quo assumenda. Magni quidem saepe sapiente non aut facere inventore. Cum neque reprehenderit voluptatem est.', '2016-03-21', 'Gerhard', 'Ipsam sed nobis ab laudantium reprehenderit. Aliquam natus in commodi minima et ut rerum. Dolorem labore sed quo dolorum provident aliquid esse. Officia error officiis molestiae repellat magnam.', 'tmp//39ec98af87fc64e10c838e90671cd4d6.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (12, 'Consequatur dolores tempore perferendis eligendi ipsam. Maxime dolore molestiae aut minus neque quibusdam molestiae. Vel excepturi libero in sequi nemo dignissimos.', '1971-08-29', 'Emmanuel', 'Et reprehenderit enim reprehenderit atque id odio soluta. Tempore cupiditate assumenda odio doloribus sunt consequuntur. Atque ab deleniti omnis iure et eum voluptatum. Iusto accusamus architecto ea.', 'tmp//5c4bbeb1515a0db0b650bf0fb08a742d.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (13, 'Laborum dignissimos dolores tempora nulla impedit. Nihil sint hic nobis temporibus ut est. Vel animi veniam quae omnis.', '1972-04-09', 'Nasir', 'Aut nam neque nesciunt architecto ea. Assumenda qui quidem rerum et minima sed sequi.', 'tmp//aa3b9499f2497d2fba631525b5d996df.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (14, 'Neque suscipit mollitia illo rem. Consequatur ab unde corrupti ducimus ex. Mollitia qui illum quia tempore assumenda aut.', '1973-10-08', 'Sam', 'Praesentium optio consequatur vel repellendus et dicta dolorem. Laboriosam eum autem totam. Est eos voluptate molestiae ut.', 'tmp//04675d465aa51321b1507eb289cc1bb9.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (15, 'Ipsa suscipit dolore sapiente commodi. Sint qui doloribus dolorem. Voluptates vitae tempore necessitatibus et eveniet. Ut nisi et laboriosam et eaque facere.', '2007-01-06', 'Everardo', 'Et modi voluptas quia qui dicta minima dolore. Nulla veniam aut in labore est quaerat rerum. Provident est qui aut est. Quod animi ipsam dolore quis iusto.', 'tmp//95afc7a07f22b1604a2a054ce767dbe5.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (16, 'Dolores nihil quia repellendus velit officiis. Ducimus vel ipsa eius. Explicabo quo ad error animi. Quo perspiciatis ex reiciendis maxime doloribus tempore est maxime.', '1989-05-15', 'Drake', 'Consectetur et qui quia qui aut dolorem. Ducimus accusantium non nihil rem. Quaerat consequuntur saepe sequi et ad earum.', 'tmp//54d8fdf5d90637e5556cd2ea59179404.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (17, 'Neque commodi qui voluptatibus a totam et. Quia consequatur modi ipsa et reprehenderit officia et enim.', '2006-03-28', 'Tod', 'Voluptate debitis voluptatem atque aut omnis. Voluptatem quo aperiam qui sint fugit. Autem amet sed ut consequuntur voluptas eveniet. Quis vel enim sed perspiciatis.', 'tmp//81b236cd511b014707ff54bf4e448945.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (18, 'Voluptate velit inventore totam in. Tempore et ex officia. Animi beatae ut sequi dignissimos pariatur. Ad aliquid commodi eos unde deserunt.', '2009-12-21', 'Nathanael', 'Vitae sequi sed ea ea expedita vel dolores libero. Occaecati voluptatem error consequuntur dolores et. Incidunt in quia labore aut dignissimos minus nisi.', 'tmp//34be0dc08eff98b25517a34b8e0886a9.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (19, 'Corporis ut ipsa dolor quis est consequatur. Nihil voluptatem omnis debitis temporibus. Repellendus facilis molestiae iste ut.', '1999-05-21', 'Arden', 'Et nam quia id ratione at. Adipisci consectetur rerum dolore est. Velit expedita iure explicabo possimus eos fugiat itaque. Soluta vel reprehenderit dolor aut.', 'tmp//fd2328013df984036ab00fb6657620ce.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (20, 'Sit dolorem et eligendi id molestias. Amet ratione voluptatem qui laboriosam consequatur atque. Et incidunt nihil est optio rerum nisi natus. Rerum nemo nesciunt enim quibusdam voluptatem commodi.', '1991-05-03', 'Alessandro', 'Aspernatur fugiat sapiente vero. Illum facere omnis tenetur similique. Quos non officiis omnis recusandae exercitationem quos consequuntur. Quia et iusto omnis et architecto sequi ut.', 'tmp//64e8985c02eecd33d15b3add75b83052.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (21, 'Eveniet adipisci harum blanditiis aut incidunt autem accusantium. Amet officia ea ipsam vel. Est deserunt atque nihil voluptatem ea non. Id dolores ipsa sed eius quae enim eos magni.', '1995-03-03', 'Ludwig', 'Distinctio natus ex quisquam repellendus minima at. Voluptates minima deleniti sunt alias. Et sit cum voluptas officia soluta eos.', 'tmp//82d6f281b4773d6fa27d2f1bab3b1f7b.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (22, 'Quia qui est mollitia quaerat doloremque. Amet delectus delectus nam ea laudantium iusto occaecati. Et mollitia quo nihil suscipit voluptas. Sit et voluptatem cupiditate.', '2010-11-24', 'Dustin', 'Distinctio distinctio voluptate odio excepturi est. Rerum dignissimos dignissimos atque ut. Similique illo ratione et eum. Facilis voluptas ducimus ratione omnis qui.', 'tmp//f2eb0e35bc008f96de33d6505383b15f.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (23, 'Minima sunt saepe qui temporibus modi repellendus ipsum. Quia dolorem quam perferendis voluptatem consequatur. Eos occaecati deserunt in et ipsa. Et nam omnis veritatis rerum voluptatum.', '2010-12-07', 'Jerrell', 'Qui ut laboriosam excepturi adipisci. Nihil vitae vel dignissimos fugit fugit. Doloribus veritatis tenetur voluptatem neque.', 'tmp//936bf9c995eab782cbcebb5501dac7d9.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (24, 'Repellendus quam et adipisci tempore architecto iusto et. Quisquam optio aut rerum tempore.', '1989-09-08', 'Jeremy', 'Est alias sed explicabo voluptatum magnam eius quibusdam. Sed sint quo quo officia reprehenderit.', 'tmp//04ed3b641d94690f5fd1c57837362857.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (25, 'Id facilis itaque quam et omnis magni fugit et. Ut sed quo consectetur est inventore aut. Commodi magnam odio nisi est vel.', '1977-05-20', 'Jamir', 'Voluptatem neque vel aut soluta. Explicabo et est impedit aut labore ut. Distinctio dignissimos magnam officiis assumenda sit quisquam aut cum.', 'tmp//389f022a34c4eeaca1416374f9671327.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (26, 'Facilis nihil neque illum. Aliquid aut ut veniam quia ut illo sit. Dolore saepe ipsum ut alias. Quia facilis sed aperiam repellendus aperiam officiis.', '2017-10-22', 'Zackary', 'Et ex nulla voluptate ut autem possimus earum. Dicta ad est accusantium eum sunt sed dolor.', 'tmp//40b2bfd1257f1fd0648654e7924775b0.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (27, 'Facere quasi enim tenetur consequatur est enim fuga dolores. Voluptatibus consequatur doloremque aut ad numquam rerum. Aut et culpa eaque maiores aut quidem quos eaque.', '1997-08-22', 'Deon', 'Voluptatem ea omnis corrupti sint maiores occaecati. Perspiciatis unde fuga facere magnam velit ea repellendus. Corporis quasi dolor qui natus.', 'tmp//d5c25001407910b6633e163a52eaee81.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (28, 'Voluptatem ipsa pariatur ut consequuntur consectetur sed. Totam minima nihil fuga ut. Necessitatibus debitis illum nisi minima eveniet aut ab occaecati.', '2000-07-02', 'Braulio', 'Eligendi provident assumenda tempore et. Voluptate aut ex corrupti sequi porro aperiam. Voluptatum voluptate aut sint saepe excepturi recusandae in. Voluptate tenetur et et omnis ex.', 'tmp//a68670585eda128c645af21724ae3d36.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (29, 'Qui id quos omnis accusantium praesentium. Repudiandae dolores et impedit ad est est. Ducimus magni nesciunt molestias impedit quos.', '2011-10-28', 'Claud', 'Quo dolorem blanditiis ut aspernatur neque. Harum quia quo vitae adipisci aliquam ut qui. Eos aliquam eligendi dolore. Sed sunt repellat non.', 'tmp//03b33889b8b51834a0fe0675da96a046.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (30, 'Non nobis sit in minima magni pariatur. Qui id qui ipsum. Sapiente in ipsa doloribus.', '1992-12-06', 'Peyton', 'Ipsum magni nemo veniam aperiam veniam amet similique molestias. Fugiat rerum consequatur accusamus. Ut culpa at voluptas voluptatum. Dicta sit fugit voluptatem ab.', 'tmp//5c7da1d6aa78bd03837f67b9414c8119.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (31, 'Atque inventore quasi impedit ut consequatur odit officia. Accusantium est aliquid blanditiis excepturi labore. Iusto soluta exercitationem at aliquam expedita a amet non.', '1987-12-19', 'Cyril', 'Et unde quia voluptas vitae in alias iste. Consequatur ullam eaque cupiditate totam non. Et porro ipsa dignissimos.', 'tmp//23dca0deaf7d10bed8f1ac57e0303a9a.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (32, 'Facilis totam est est impedit quis adipisci. Quod dolor praesentium et quia ad ut voluptatum sunt. Quod quia perspiciatis dolore voluptate sed ipsam.', '2018-01-15', 'Kristopher', 'Hic quia ea et rerum magnam quia iste. Voluptatem vero atque a. Consectetur quas accusantium nulla temporibus sint. Rerum nostrum reprehenderit repudiandae qui assumenda.', 'tmp//cff332b3c8bb5ada3f9621c169478b85.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (33, 'Nihil voluptatem totam fuga. Alias reprehenderit praesentium veniam sit voluptas. Fuga et commodi consequatur magni in ex.', '2014-08-14', 'Scottie', 'Iusto dolorem occaecati ullam sunt est vel. In dolorum ducimus ea pariatur earum sapiente. Expedita provident tempore et nemo. Quis aut odio optio voluptatem labore nostrum.', 'tmp//4857a35b666a17969da8bae8063194a5.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (34, 'Rem id facere alias expedita nobis corporis pariatur et. Ea deserunt iusto dolore animi sapiente. Quia dolor dolor qui consequuntur tenetur nihil qui. Architecto et non in non sequi praesentium.', '1971-01-27', 'Jacques', 'Nisi fugit porro non reiciendis. Sit maiores non doloremque eligendi. Est id nihil est eligendi itaque saepe eum deleniti.', 'tmp//5e5ce7ef0449b07d453d7d03678af348.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (35, 'Voluptatem eligendi sed est eius. Aspernatur quia tempore vero nihil sed ducimus est. Maxime accusantium nihil est rerum laborum quod. Temporibus sit amet enim earum est dolor quis.', '1992-11-05', 'Boyd', 'Ipsam quia et dicta accusantium facere. Sunt velit aut veritatis ipsa dolorem illo omnis architecto. In exercitationem praesentium quo accusantium molestias ad.', 'tmp//62861fabb1ddbe5b67b66f572130469c.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (36, 'Quis iusto rerum officia tempora. Velit corrupti magni aspernatur dolorem. Consequatur in sit perspiciatis officiis sed. Magni error ducimus sit suscipit neque.', '2013-08-19', 'Jerald', 'Vitae autem dolorem provident quis delectus autem qui sunt. Similique quia odio at sit. Repellendus delectus quam cumque ex excepturi iste. Vel quia et nulla quisquam sit eos officiis.', 'tmp//281b8d403a35f90858656cfc37118a78.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (37, 'Hic perspiciatis ut tempora ipsa id esse reprehenderit. Qui sit quaerat cupiditate facere. Sequi voluptatem id quis optio animi officia. Esse labore quo expedita enim similique.', '1973-10-14', 'Carmelo', 'Esse vel quia autem optio. Molestiae sapiente labore ipsam ut sint aperiam quaerat. Adipisci eos aspernatur recusandae sed qui quo sit quis.', 'tmp//e3e9048ada6b1ec778e5a727a5075096.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (38, 'Ut adipisci earum laborum voluptatem voluptatem aut esse. Quibusdam voluptatibus magni facere aliquam nihil pariatur. Earum cumque aut ut.', '2015-01-22', 'Mckenzie', 'Ducimus qui aliquid sed qui ut et nulla. Libero optio quod placeat. Ut ut voluptate voluptatibus. Facere sint aut id et sapiente.', 'tmp//75a8a509bb7f8d01f0a3390c79cbfc0d.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (39, 'Quae alias vero et laborum porro illo. Ipsum vitae quia maxime. Praesentium voluptate qui numquam recusandae. Exercitationem officiis aliquid vero debitis.', '1983-08-09', 'Imani', 'Molestias dolorem nihil odio et voluptas assumenda. Recusandae possimus quis ab nihil explicabo quaerat et. Vel aut consectetur et vel et sed.', 'tmp//0b9cf08a290966b6ad935e15226c6b0b.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (40, 'Nihil omnis expedita architecto quibusdam est nisi. Omnis perspiciatis laborum impedit minima quidem. Modi ad quae veniam nobis.', '2006-07-24', 'Dewitt', 'Dolore minus corrupti et optio. Aliquid eos quod dolorem voluptatum officiis. Iste impedit quaerat qui voluptatem.', 'tmp//e312fb001c1257b9e7cccbe599a6283f.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (41, 'Consequatur modi quo a maiores alias. Numquam quidem quidem quam dolorum veniam ut quasi. Ducimus delectus et laudantium quae harum cupiditate atque. Aliquid ipsam itaque provident soluta recusandae.', '1974-06-18', 'Major', 'Est ea recusandae saepe molestiae voluptatem itaque nihil. Ipsam aliquid ea laborum harum blanditiis veritatis. Fugiat dolorem dolorem laborum est nam sint.', 'tmp//603d28c652ffbc04e5c26710936e1091.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (42, 'Ut quidem minima aut sunt eos magnam minima. Nostrum sed voluptatem ut dolor quis et. Nam eaque esse voluptatem ut eum.', '2004-03-14', 'Stephen', 'Omnis autem esse enim amet et unde. Repellendus repudiandae numquam nihil fugiat temporibus. Ut eius voluptas non non.', 'tmp//8ba9709efb010fe24a4a83d40b439f0d.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (43, 'Autem aliquid qui est sunt necessitatibus at. Eaque rerum non dolor laborum aut voluptatem sed. Repudiandae unde quia quod. Hic et consequatur provident suscipit numquam sed at.', '2013-11-29', 'Mason', 'Pariatur sed deleniti et ea labore. Harum dolores culpa quo reiciendis. Et placeat sapiente ut totam commodi soluta dignissimos. Aut similique in ullam et libero nobis consequuntur.', 'tmp//a8b03c598e1b2809d582b5e6e729ff4c.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (44, 'Sunt soluta ratione deserunt ducimus voluptatem. Repellat mollitia ab aspernatur minima eum officiis et. Qui veritatis dolore maiores voluptate. Eius voluptas et qui harum.', '2018-02-19', 'Enrico', 'Est repudiandae necessitatibus praesentium. Autem sit ducimus ut quis ducimus sit dolorem architecto. Voluptas libero est ipsum libero officia aperiam.', 'tmp//8a488091fbedbae15afaae79b8dbd180.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (45, 'Ut et omnis beatae ut dolorum autem aliquam. Magnam modi ratione totam animi. Unde distinctio hic itaque in officiis vero quisquam nesciunt.', '2018-05-14', 'Olen', 'Non eos nihil ex corrupti quia consectetur nemo. Saepe velit et ea odit sed id beatae pariatur. Qui quo dolorem quae qui doloremque libero inventore iure.', 'tmp//88758ce2e4f9719c4565823d20e6da62.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (46, 'Consectetur debitis facere id quaerat exercitationem ad. Nisi mollitia porro cum. Reiciendis est sint optio quia fuga libero sed minus. Quia praesentium vel esse praesentium.', '2014-09-29', 'Consuelo', 'Culpa saepe aut natus inventore ea. Quas adipisci aut omnis quis quos. Velit odit repellat velit temporibus unde.', 'tmp//2d9094bcc67aa939eaf778d3f508651d.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (47, 'Rem laborum consequatur velit in iste voluptatem. Voluptas laudantium assumenda odit voluptate unde in aperiam. Quibusdam consequatur totam iusto voluptatem est hic nisi. Est repellat voluptas sit.', '2012-10-03', 'Lazaro', 'Expedita ratione sint ut eaque. Sit blanditiis voluptas aut mollitia laboriosam. Voluptas ut ipsa ullam quis et.', 'tmp//174412a9dcf00fd91f45286d192a974f.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (48, 'Quaerat enim ab itaque. Pariatur dignissimos facere ullam laboriosam. Vitae blanditiis soluta sint exercitationem.', '2011-06-29', 'Barry', 'Hic consequatur dolore voluptates. Id quos voluptatem fugit qui harum ipsam.\nNemo ut magnam debitis necessitatibus. Nesciunt autem aut et. Quam et nihil ipsam totam omnis rerum optio.', 'tmp//9fd558925733d58b5dfb9b633843b6a1.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (49, 'Delectus ut est nemo modi aspernatur qui fugit. Recusandae voluptas sed provident magnam ut culpa doloremque. Vel perferendis nesciunt totam rerum sunt facere.', '1983-08-11', 'Jessie', 'Velit et eaque corrupti ut. Ea nemo blanditiis ratione. Nesciunt cumque vel ipsum nesciunt laborum. Doloribus ut expedita aspernatur voluptatem temporibus.', 'tmp//02102b1e500aaa7d873bf681a0a4faf9.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (50, 'Aut ut velit magnam sit et voluptatem. Quia illum dolorem vel qui ut harum ut. Doloremque non est praesentium vel quis non velit.', '1973-09-21', 'Garland', 'Tempore molestiae deleniti ut nihil id et. Id laborum velit cum saepe aut. Eaque et rem aut atque aut vel nihil. Et quis perspiciatis sit vero nobis eos error.', 'tmp//26ee4728fb9dc4c1770f37d2753e2fd9.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (51, 'Reiciendis dolorem inventore quod minus aliquam nisi porro et. Culpa necessitatibus ut aut qui. Aut quia ut dolore et.', '2003-03-27', 'Zion', 'Ea ut in aut eos dolore magnam. Ea assumenda harum et. Error provident quasi voluptas.\nAd qui tempora corrupti eaque est. Iste hic illo quis quo necessitatibus. Deserunt quia labore ipsum.', 'tmp//ef9e420bdba036bcf3ac5826817e0809.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (52, 'Consequatur nemo velit doloribus voluptate quod. Culpa deserunt eveniet maxime. Quo ut ducimus et debitis sunt. Sed ipsam et animi provident ex et praesentium.', '1974-11-15', 'Kameron', 'Dolore veniam sunt mollitia aut in aut omnis. Est aperiam error ut aut voluptatem. Ut aut inventore minus consequatur fugit rerum.', 'tmp//9205f62934ef8d88fc48374a32947a25.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (53, 'Et nostrum quis ut ex. Illum qui non molestias eaque provident aut. Incidunt temporibus architecto alias ratione voluptatem quidem.', '1987-06-30', 'Rory', 'Earum ad iste alias corrupti sit nihil ut. Aut qui aperiam et quia. Et magnam quam est suscipit itaque. Praesentium iste magnam eos reprehenderit est.', 'tmp//163f5a8668bd61bbbdf0a79231de05bc.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (54, 'Illum qui quia similique consequatur optio mollitia. Accusamus doloribus sunt veritatis quisquam iusto quia amet voluptatem. Distinctio consequatur omnis sed beatae.', '1978-04-03', 'Dustin', 'Occaecati deserunt excepturi nihil et qui molestias. Eius quas expedita perspiciatis placeat minus ipsum quidem.', 'tmp//c057df9a25bef66530d92d00f0095e75.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (55, 'Ipsam repellendus eaque beatae similique est aliquam aut cumque. Est incidunt enim blanditiis quaerat aut omnis minus. Quibusdam consequatur itaque harum vel quis adipisci.', '1994-03-20', 'Brice', 'Enim similique non facere ipsam quidem quaerat nihil. Quos aut suscipit odio placeat impedit. Aliquid laudantium voluptatem autem dolor. Iure mollitia non qui totam modi optio.', 'tmp//f1f9f59414661d2850150835ffdb11ab.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (56, 'Architecto aperiam tenetur eos cupiditate beatae itaque minus. Eos debitis eos non officiis aut est sint. Qui accusantium atque nesciunt eius.', '2010-04-03', 'Jaylon', 'Ratione sit minima ut harum nostrum. Occaecati at ipsa enim suscipit.\nDolores dolor omnis et cumque. Quisquam maiores dignissimos ea architecto et. Quo voluptate pariatur doloribus.', 'tmp//b790f326a23c628e95f45cd3ff9475f7.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (57, 'Ut amet nihil et. Modi et aut totam facere. Consequatur aut non laboriosam. Porro fugiat vitae minima enim exercitationem.', '1978-08-01', 'Samson', 'Debitis itaque id iure omnis vero. Consequatur et similique placeat ipsam consequuntur occaecati. Voluptatem eos aperiam et voluptatum libero unde. Quo maxime quaerat illum sequi minus est quaerat.', 'tmp//24ff2a4a80c45cca01f0d71c77dfba84.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (58, 'Doloribus ut non nobis suscipit minus suscipit. Nulla culpa suscipit officia aspernatur laboriosam est id.', '1978-12-23', 'Hayley', 'Placeat cum dignissimos et aliquam velit magnam itaque. Et ut necessitatibus occaecati magni aliquam est. Adipisci nobis id molestiae alias aut hic voluptates.', 'tmp//d4d56b67cfe7adf3de7f62dba04b50ba.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (59, 'Ut sapiente autem explicabo laudantium. Voluptas unde impedit possimus aut. Saepe voluptates accusantium facilis numquam id voluptas. Maxime itaque cum voluptas.', '1995-06-05', 'Josue', 'Quod fugit dolores dolores illo est. Eius cum cum dolor molestias. Molestias sed qui recusandae incidunt totam omnis reiciendis fuga. Ratione autem facere minus esse totam ut.', 'tmp//2f8a457afb5d8e06b63d0ed2fcfec7af.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (60, 'Quis ipsum hic quasi adipisci vitae veritatis quidem aspernatur. Ab voluptatem in soluta. Qui sunt est omnis neque facere. Quos consequatur optio unde.', '1997-03-06', 'Maximus', 'Eaque et assumenda earum. Aut quia voluptas consequatur architecto. Repellendus voluptatem quis unde nostrum odio. Temporibus quas recusandae iure voluptas accusantium non consequuntur cumque.', 'tmp//f32c58985d96dd2e73c524b5550b6f03.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (61, 'Qui quis sint ut quae voluptatibus delectus debitis. Dolor blanditiis odit accusamus. Autem sit ducimus voluptatem id. Nisi in aut vel dignissimos rerum.', '1978-05-02', 'Turner', 'Eum quidem enim eum accusantium veritatis et eos. Consequatur enim consequatur doloremque. Sit veritatis facere porro et voluptas nesciunt voluptatibus.', 'tmp//c8ab2fbbae1addd75bc16bb376656f13.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (62, 'Tenetur eligendi est at. Illum beatae ad tenetur. Ex consequatur temporibus blanditiis. Voluptatum quia eaque alias cumque occaecati.', '2014-01-07', 'Alan', 'Omnis et atque voluptatem nobis voluptatem. Officiis est animi sapiente consequuntur. Et velit rerum et asperiores quidem aperiam.', 'tmp//1abc72c4fd1924a6e363eef611f48f6f.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (63, 'Nihil dolores qui iste. Facilis ea unde sapiente eius. Natus eaque consequuntur nostrum eaque. Vel enim voluptatem molestiae qui perspiciatis soluta enim.', '1996-06-21', 'Tatum', 'Ut ex voluptatem nam laboriosam. Provident voluptatum incidunt consectetur voluptas quia delectus fugiat. Perferendis sapiente officia et corrupti eos.', 'tmp//e024a86284fb217febf9d4ab998a86fc.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (64, 'Non nesciunt et nemo vel quas distinctio. Esse et facere cupiditate rerum in. Ea dolorem unde nulla. Veniam expedita vel quasi molestiae quis explicabo molestiae.', '1974-08-08', 'Shane', 'Iste nostrum odio ut ea voluptatem et quaerat error. Aut veritatis inventore sunt nulla. Perspiciatis itaque iusto quis rerum nemo.', 'tmp//ce4ae5e688e4bf04b01f5a632d49bd28.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (65, 'Earum soluta minima omnis. Consequatur exercitationem enim repellat. Odio earum mollitia officia doloremque id ut quia possimus. Voluptatem iste qui cumque dolores.', '1995-12-04', 'Izaiah', 'Voluptates sint dolore sapiente magni animi porro nisi maiores. Laboriosam rem hic quia distinctio voluptatem illum. Ducimus perspiciatis recusandae sunt. Aliquid unde quo et sit.', 'tmp//d891ef58a30f47d4844e6b388efcaf98.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (66, 'Inventore dolores neque qui itaque consequatur repellendus. Autem odio placeat culpa veniam atque voluptate. Omnis fugiat modi sed doloribus. Labore et delectus eum sint voluptatem.', '2008-01-20', 'Hayden', 'Id repellendus explicabo quos id. Nisi rerum dolores commodi facere est. Dolore recusandae at ut doloremque. Expedita doloremque blanditiis dolorum.', 'tmp//4f6e79ac618aba294954356d70402fb5.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (67, 'Quos ut quidem in suscipit eum magnam. Aspernatur est sapiente esse et. Excepturi nihil laboriosam nemo eos molestias maiores placeat. Cumque voluptatem quo ea eaque quibusdam et.', '2011-05-01', 'Xander', 'Voluptate molestias autem non nobis est sunt hic. Consectetur harum laboriosam officia ut vel ipsam ex. Commodi quia enim repellendus. Cumque sit est hic eos distinctio.', 'tmp//e40e160971ae69d2c42e58c0a9a323dc.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (68, 'Repellendus molestiae incidunt eum. Ratione est ea atque. A ut omnis ut quisquam distinctio. Voluptatem est sit temporibus sit aut.', '2008-06-05', 'Sylvan', 'Error animi perspiciatis vero nihil voluptatem est sequi. Quo iusto veniam est. Quod et repellat odio reiciendis. Voluptatem sequi omnis exercitationem excepturi ut.', 'tmp//4df263c69cc066c1bb85179398495e81.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (69, 'Nemo sit ipsum quis. Qui autem quas laborum incidunt architecto labore molestiae voluptas. Iste animi quidem voluptas eos.', '2000-06-26', 'Lesley', 'Non deserunt ut maxime quibusdam aperiam. Iusto voluptas eos minima delectus. Occaecati facere quo eaque dolorum.', 'tmp//186334d568143d8d1dadb8db0686d777.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (70, 'Accusamus beatae nemo fugiat vel iure. Voluptate maxime qui voluptatibus culpa reiciendis. Expedita earum ea nemo facilis.', '1984-07-08', 'Michel', 'Minus blanditiis quasi pariatur reprehenderit eos beatae. Eum molestias nesciunt aliquid et. Cupiditate in esse voluptatem accusamus dolorem consectetur est.', 'tmp//d8edbb91d5ece50caa35e076799eb9af.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (71, 'Et consequatur quia et autem voluptate praesentium. Voluptatem repellendus sunt minus debitis exercitationem. Consequatur et quas pariatur non consequatur.', '2002-10-28', 'Niko', 'Cum qui sequi sit occaecati numquam. Omnis ut recusandae voluptatem voluptatem quam molestias dolores. Excepturi eos et dolorum aliquid cupiditate tenetur. Debitis et non ex at aspernatur a.', 'tmp//668396f604f5cf73b1fa5177e60fec85.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (72, 'Quo quis eum dolor. Et pariatur nam sed dignissimos. Culpa ratione veritatis quis quas omnis assumenda maiores. Libero ratione explicabo dolorem aut iure esse esse dolorum.', '1981-12-16', 'Brandon', 'Omnis placeat dolore sed ratione nostrum ut aut. In blanditiis quam nulla saepe sint sint aliquid. Dolores animi reprehenderit id qui.', 'tmp//586b00021b92c14731b6e8756460248a.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (73, 'Praesentium omnis et veniam in tempora et. Omnis quo doloremque est quia illum aut quia veniam. Suscipit impedit quisquam quae magnam. Consequatur eos rerum ducimus et iure.', '1994-03-11', 'Evert', 'Alias hic odit laborum magnam. Magni sit praesentium quidem nisi fugiat iure. Ipsum ab et et qui laudantium aspernatur nulla.', 'tmp//4f6051e551c751984a7770463b6488b1.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (74, 'Ut nam veritatis sequi. Quae voluptatem et repellat. Adipisci quaerat numquam magni doloribus nulla. Qui voluptate ut unde fugiat soluta excepturi.', '2006-10-20', 'Jaiden', 'Blanditiis illum quam rerum et quia dicta sit. Molestias modi corrupti ut excepturi ut ad ut. Sunt et unde et aspernatur suscipit. Aut sed ipsa dignissimos aut corporis vel perferendis.', 'tmp//aed7185c578cffc8e18d5c3092e9e14b.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (75, 'Eligendi corporis rerum sint velit enim alias. Nobis est architecto asperiores blanditiis qui autem. Velit consequuntur vitae ex tenetur odio qui.', '1973-10-08', 'Keanu', 'Est facilis odio itaque provident. Suscipit sed qui eum. Voluptatum totam sed impedit ut rerum est iusto quam.', 'tmp//23affdd538f883d6853e12e3c4cfbd18.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (76, 'Totam rerum exercitationem distinctio rerum deleniti dignissimos velit. Sunt rerum nisi laudantium neque est harum.', '2017-04-29', 'Michale', 'Non enim non culpa velit vel. Et saepe voluptatem ipsum. Quisquam unde dignissimos rerum sit ullam. Qui et consequatur dolores hic nulla. Soluta animi ab deserunt veritatis qui eos.', 'tmp//7926876463f2a878a2888f170ecca57b.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (77, 'Fuga et sed sequi sit delectus quidem blanditiis quas. Minus iure vero excepturi laboriosam dolore ut. Non est occaecati ut consequatur. Magnam aspernatur consectetur id consequatur eum et eos.', '2010-05-04', 'Kendrick', 'Et similique autem cumque accusantium. Doloremque quas quibusdam non explicabo. At itaque iure totam sapiente ad. Ducimus culpa praesentium labore recusandae assumenda velit enim.', 'tmp//52b8e9125c1505a002471a0df725f89e.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (78, 'Dolores nobis et temporibus rerum. Ratione est amet nam facilis saepe sapiente nesciunt id. Voluptatum quaerat sint corrupti eos pariatur. Occaecati porro officiis eum blanditiis est et quo.', '2018-10-27', 'Ansley', 'Dolor nihil maxime quod neque officia ea cum. Voluptas et officiis totam explicabo cum magni. Voluptas et doloremque amet autem voluptas. Dolorem et quo exercitationem nostrum est et.', 'tmp//acbd60dc5c6e61ed67a64a702908a37c.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (79, 'In fugit quos officiis. Temporibus sint aut odit quam. Eligendi et et facilis hic in qui. Quia odio voluptate itaque harum molestiae numquam. Veniam velit tempora corporis mollitia.', '1996-09-12', 'Cloyd', 'Reprehenderit ut reprehenderit et modi. Voluptate libero ut est velit culpa aperiam. Cum et rerum officiis sint quia.', 'tmp//c95865ffa45cb7382002fe12998e1832.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (80, 'Sit cupiditate non culpa eos molestiae. Quia molestiae est eum at tenetur quibusdam. Repellendus placeat natus dignissimos omnis. Culpa sed explicabo modi est quis quod est.', '1973-11-18', 'Carmelo', 'Corporis et quis culpa aut alias assumenda. Commodi omnis sed dolores minus. Et vel et et doloribus omnis illum.', 'tmp//5c7d28bc2da03a2ebefd43ee3798048b.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (81, 'Autem autem eum modi. Tempora eveniet facere et temporibus et cum ea quo. Molestiae assumenda eius error ut libero ut quasi.', '2009-06-03', 'Timmothy', 'Et odit voluptas molestias cum unde excepturi itaque distinctio. Reprehenderit voluptatibus et molestiae dolores quidem. Et magnam voluptatem ad libero et aut.', 'tmp//2f977fbe61cd0ae6f15daabf255b554c.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (82, 'Qui sit consequatur sit modi molestias ducimus consequatur. Nisi ratione eaque omnis illum quia aut. Eius deleniti quae natus praesentium qui. Vero quisquam nobis nam.', '2004-02-24', 'Keagan', 'Rerum incidunt voluptates aut deserunt voluptatem qui et. Similique suscipit quia sapiente quas sequi explicabo. Mollitia animi necessitatibus ipsum voluptate qui provident.', 'tmp//2b5a7d414998cd7fc47ec73ffd79c2dc.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (83, 'Soluta eligendi laborum eos. Atque in architecto quisquam autem quidem iste. Quia tempore officiis sint veniam.', '1986-03-27', 'Uriah', 'Error corrupti sit alias facilis provident nihil. Voluptas est deserunt debitis neque. Et explicabo molestiae ut.', 'tmp//67c85e7996acfc260f43a50731f78944.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (84, 'Eius omnis dolores voluptate. Atque illum voluptates quis illum voluptatem non. Tempore soluta magnam vitae eveniet ut ut quia. Praesentium non vel voluptatum quae.', '1981-03-17', 'Hyman', 'Nam rerum consequatur officiis ullam nostrum. Labore vel et illum. Nobis consequatur ut dignissimos et molestiae.', 'tmp//5c6ce1f2659da24517dc9c88806684e0.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (85, 'Ea impedit dicta qui eum nemo consequatur ea. Voluptas eius minus dolorem ad voluptate sed eligendi.', '1980-07-27', 'Saul', 'Omnis deserunt reiciendis aspernatur ea ut. Et et rerum aut facere cum sit sunt. Voluptas quod animi quasi necessitatibus doloribus animi. Delectus omnis sed aut nam officia dolores consequatur.', 'tmp//d8daf84db9c1d1e1853c4ba99548a7d3.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (86, 'Quidem quae molestias qui minus quae consectetur neque. Et consequuntur possimus earum illo ea eum sit maiores.', '2014-10-09', 'Johnpaul', 'Accusantium dolore quis optio et necessitatibus doloremque quos. Illum voluptatem soluta fugiat eligendi et. Iste voluptas architecto eos aliquam. Veniam molestiae repellat rerum facere eum.', 'tmp//d7d7517953c8e654171641af8abf4f55.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (87, 'Perspiciatis at cumque animi odit tempore dolorem ullam. Quae quia ipsa et beatae iusto at. Doloremque dolore error perferendis sit.', '2010-03-07', 'Kiley', 'Et neque id aut voluptatum commodi aut explicabo. Ut ea eos voluptatem eos fugit. Facere et ut hic vero iusto eos aliquid. Sed minus quis et exercitationem animi.', 'tmp//48ee2c12e3c1701330a13f41e496ca0c.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (88, 'Provident doloremque ratione pariatur et. Voluptates vel qui sapiente. Quod odio in fugit vitae ex.', '1970-11-05', 'Zachary', 'Amet id molestias ullam dicta. Ut aut aspernatur quibusdam. Corporis accusamus dolores cum commodi et aut. Quo ea ipsa laborum quis et cum voluptatem.', 'tmp//7a958b158dd33aec18c6e6c8734ab497.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (89, 'Temporibus molestiae et consequatur voluptatibus quia. Similique aspernatur sapiente sed. Quia a sed quam eum esse velit laborum.', '1973-09-09', 'Kaleigh', 'Quo et esse nihil est rerum molestias. Aliquid praesentium sit id quis deleniti. Reprehenderit possimus nihil quibusdam nihil suscipit voluptate aliquid.', 'tmp//f988afb8e9a27e69fc1e9d04caebaf80.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (90, 'Id architecto occaecati et nemo qui. In in qui non sapiente et atque dolores. Occaecati necessitatibus a rem deleniti qui sed sunt.', '1997-12-23', 'Arno', 'Omnis debitis quia consequatur adipisci veniam non praesentium et. Explicabo quia cupiditate placeat enim et sed eum.', 'tmp//7161c0bb5aef81ead5b6f27873f82114.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (91, 'Porro et ullam illum ipsum et nam rerum. Esse quidem nam est voluptatem in. Quibusdam ut nihil maiores voluptas rem.', '1978-06-07', 'Darrin', 'Quisquam in et voluptatem. Eos et quidem et vel quis. Consequuntur nisi labore nam.', 'tmp//bff875f3f452833c85eaf60b26fcfc2d.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (92, 'Adipisci sint odit reprehenderit sit vel minima. Sit quo quidem molestias. Temporibus earum et aliquid voluptatibus rem.', '2015-04-03', 'Macey', 'Possimus eveniet mollitia mollitia cumque molestiae incidunt ipsum. Est totam vero natus quas et aut. Est dolorem qui numquam non sit tempora voluptatem.', 'tmp//3075db8fb36711211e59d0b0c7f3b9b3.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (93, 'Ut deserunt vel deserunt modi. Corrupti velit doloribus architecto iste. Corrupti repellat ut perferendis et quo sapiente tempora possimus.', '2018-05-21', 'Johathan', 'Tempore temporibus dolorum et quo fugiat accusantium tenetur vitae. Ex provident et sit. Praesentium ad voluptas aspernatur placeat ea qui. Consequatur et commodi mollitia consequuntur ullam ut.', 'tmp//f70b175cbacf7eea2c68645bec95c689.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (94, 'Consequatur asperiores non aliquam facere. Sed ut laborum atque. Explicabo reiciendis consequuntur voluptas non.', '2007-08-02', 'Reed', 'Dolorem blanditiis et sapiente dicta tempore at. Aut harum nam cum aut molestiae recusandae. Et omnis minima occaecati modi quae.', 'tmp//9eae6e629b887abfa594be5b95c678ee.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (95, 'Molestiae pariatur laudantium assumenda ratione. Optio ea aut possimus. Sunt perspiciatis rerum sed commodi. Ut ipsam voluptas non voluptatem.', '1986-09-17', 'Arjun', 'Magni aliquam veritatis architecto et ratione numquam. Quis delectus sunt labore est non et. Quis facere vel enim animi molestiae.', 'tmp//e7268c976a235934fe40ae21c5b0357d.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (96, 'Ea voluptate eaque qui nostrum tempora. Impedit consequuntur error ut eum alias. Dolorum reiciendis quae nihil id reprehenderit ad. Iusto quibusdam blanditiis voluptate.', '2002-04-08', 'Darian', 'Inventore dolorem et sunt est. Laborum qui sed sint. Est delectus aliquam error consequuntur rerum beatae.', 'tmp//3a4d3836f8d66ad8c83a11c27c257788.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (97, 'Eos sequi et eius iure nihil commodi. Aliquid earum ratione quia et est et. Ipsum aut eum deserunt delectus. Ab et perferendis corporis sed perferendis quia sed.', '1980-08-08', 'Neil', 'Quam voluptas dignissimos earum facere laudantium. Sit fugiat aut impedit vel ea autem. Expedita omnis ullam inventore dolorum.', 'tmp//5754f2f56f23ed533b7dbb41f104899d.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (98, 'Commodi reprehenderit libero explicabo dolores. Vero ea possimus sed nulla et. Tenetur sit ullam fuga consequatur dolorum eligendi et et.', '1972-07-03', 'Akeem', 'Voluptatibus possimus commodi beatae ipsam. Eveniet incidunt et aut aut. Est optio ipsa nostrum adipisci. Laudantium ut et est veniam itaque et facere suscipit.', 'tmp//7f33f5af2370cfeead8ece2d719f4e4a.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (99, 'Quia assumenda tempora accusamus sit ut possimus. Architecto esse error sunt vel quia quas beatae. Voluptas et alias repudiandae nemo dolorem. Ab itaque odio voluptas dolor vel rerum quas.', '2015-05-07', 'Nash', 'Laudantium molestiae et molestias labore repudiandae rerum est. Libero autem et provident harum ut ea eius unde. Voluptas ut vitae illum repellendus.', 'tmp//b7eff0b11ea7b9f84c306eaeea3fc140.jpg');
INSERT INTO `books` (`id`, `title`, `date`, `autor`, `description`, `image`) VALUES (100, 'Occaecati placeat sit voluptas deserunt libero sequi. Quod laudantium et et temporibus consequatur suscipit enim. Ducimus reiciendis qui ea et et. Assumenda odio deserunt est animi recusandae.', '1976-12-28', 'Graham', 'Eaque ea atque et reiciendis repellat est. Sint adipisci sit autem cum corporis reprehenderit consectetur.', 'tmp//1aafea75dd9d4cdeb61b1230955c1ead.jpg');


